backend/crm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls"), name='index' ),
    path('user/', include("user.urls"), name='index' ),
    path('dashboard/', include("dashboard.urls"), name='dashboard' ),
    path('dashboard/lead/', include("lead.urls"), name='lead' ),
    path('dashboard/client/', include("client.urls"), name='client' ),
    path('dashboard/team/', include("team.urls"), name='team' ),
    path('api-auth/', include('rest_framework.urls')),
]

backend/dashboard/urls.py
from django.urls import path 
from .views import *


urlpatterns = [
    path('', Dashboard.as_view(), name='dashboard'),
]

backend/dashboard/models.py
from django.db import models

# Create your models here.

backend/lead/models.py
from django.db import models
from profiles.models import Profile
from team.models import Team


CHOICES_PRIORITY = (
    ('low', 'Low'),
    ('medium', 'Medium'),
    ('high', 'High'),
  )

CHOICES_STATUS = (
    ('new', 'New'),
    ('contacted', 'Contacted'),
    ('won', 'Won'),
    ('lost', 'Lost'),
  )


class Lead(models.Model):
  created_by = models.ForeignKey(Profile, related_name='leads', on_delete=models.CASCADE)
  created_at = models.DateTimeField(auto_now_add=True)
  modified_at = models.DateTimeField(auto_now=True)

  priority = models.CharField(max_length=10, choices=CHOICES_PRIORITY, default='medium')
  status = models.CharField(max_length=10, choices=CHOICES_STATUS, default='new')
  name = models.CharField(max_length=255)
  email = models.EmailField()
  description = models.TextField(blank=True, null=True)
  converted_to_client = models.BooleanField(default=False)
  team = models.ForeignKey(Team, related_name='leads', on_delete=models.CASCADE)

  class Meta:
    ordering = ('name',)
    
  def __str__(self):
    return self.name



class LeadFile(models.Model):
  team = models.ForeignKey(Team, related_name='lead_file', on_delete=models.CASCADE)
  lead = models.ForeignKey(Lead, related_name='files', on_delete=models.CASCADE)
  created_by = models.ForeignKey(Profile, related_name='user_lead_file', on_delete=models.CASCADE)
  file = models.FileField(upload_to='leadFiles/')
  created_at = models.DateTimeField(auto_now_add=True)

  class Meta:
    ordering = ('-created_at',)
    
  def __str__(self):
    return self.created_by.username


class Comment(models.Model):
  team = models.ForeignKey(Team, related_name='lead_comments', on_delete=models.CASCADE)
  lead = models.ForeignKey(Lead, related_name='comments', on_delete=models.CASCADE)
  created_by = models.ForeignKey(Profile, related_name='user_lead_comment', on_delete=models.CASCADE)
  content = models.TextField(blank=True, null=True)
  created_at = models.DateTimeField(auto_now_add=True)

  class Meta:
    ordering = ('-created_at',)
    
  def __str__(self):
    return self.created_by.username

backend/dashboard/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from lead.models import Lead
from team.models import Team
from client.models import Client
from profiles.models import Profile

#====================================================
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from django.contrib.auth.mixins import LoginRequiredMixin
from rest_framework.status import HTTP_200_OK
from team.models import Team
from client.serializers import ClientSerializer
from lead.serializers import LeadSerializer


class Dashboard(APIView):

  def get(self, request,*args, **kwargs):
    at = Profile.objects.get(user=request.user).active_team
    leads = Lead.objects.filter(team=at,  converted_to_client=False).order_by('-created_at')[0:5]
    clients = Client.objects.filter(team=at,).order_by('-created_at')[0:5]

    leadSeri = LeadSerializer(leads, many=True)
    clientSeri = ClientSerializer(leads, many=True)

    return Response({'leads':leadSeri, "clientSeri":clientSeri}, HTTP_200_OK)

# @login_required
# def dashboard(request):
#   at = Profile.objects.get(user=request.user).active_team
  
#   lead = Lead.objects.filter(team=at,  converted_to_client=False).order_by('-created_at')[0:5]
#   client = Client.objects.filter(team=at,).order_by('-created_at')[0:5]
#   return render(request, 'dashboard/dashboard.html', {
#     'leads': lead,
#     'clients': client
#   })

backend/dashboard/templates/dashboard/dashboard.html
{% extends "core/base.html" %}

{% block title %}
  dashboard
{% endblock title %}

{% block content %}
<div class='py-6 px-6'>
  <h1 class=' mb-6 center text-xl'>Dashboard</h1>

  <div class="flex space-x-4">
    
    <div class="w-1/2 px-4 py-6 bg-gray-100 rounded-xl leads">
      <h2 class='mb-4 text-lg'>Newest leads</h2>

      {% for lead in leads %}
        <div class="mb-2 lead">
          <h3 class='font-semibold'> {{lead.name}} </h3>
          <p class='text-xs'>Status: {{lead.get_status_display}}</p>
          <p class='text-xs'>Priority: {{lead.get_priority_display}}</p>
          <a href="{% url 'lead_detail' lead.pk %}">Details</a>
        </div>
      {% endfor %}
    
    </div>

    <div class="w-1/2 px-4 py-6 bg-gray-100 rounded-xl clients">
      <h2 class='mb-4 text-lg'>Newest Clients</h2>
      {% for client in clients %}
        <div class="mb-2 lead">
          <h3 class='font-semibold'> {{client.name}} </h3>
          <a href="{% url 'client_detail' client.pk %}">Details</a>
        </div>
      {% endfor %}

    </div>

  </div>
</div>
{% endblock content %}