backend/crm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls"), name='index' ),
    path('user/', include("user.urls"), name='index' ),
    path('dashboard/', include("dashboard.urls"), name='dashboard' ),
    path('dashboard/lead/', include("lead.urls"), name='lead' ),
    path('dashboard/client/', include("client.urls"), name='client' ),
    path('dashboard/team/', include("team.urls"), name='team' ),
    path('api-auth/', include('rest_framework.urls')),
]

backend/profiles/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import (
  # myprofile,
  ProfileListAPI,
  ProfileDetailViewAPI,
  ProfileUpdateAPI,
  FollowerListAPI,
  FollowingListAPI,
  
  UserVuzerAPI,
  NearMeListAPI,
  OrgListAPIView,
  BrandListAPIView,
  MListAPIView,
  ChannelListAPIView,

  # SavadsListAPI,
  # OrgVideosListAPI,
  # PVCVideosAPI,
  # FAMListAPI,
  remove_followerAPI,
  popular,  
  FollowUnfollowAPI,
  )

app_name = 'profiles'  # in case we need to use the namespace in the future
urlpatterns = [
  path('<str:pk>/', ProfileDetailViewAPI.as_view(), name='profile-detail-view'),

  path('allp', ProfileListAPI.as_view(), name='all-profiles'),
  path('Organizations', OrgListAPIView.as_view(), name='all-orgs'),
  path('Channels', ChannelListAPIView.as_view(), name='all-cha'),
  path('M&M', MListAPIView.as_view(), name='all-mm'),
  path('Brands', BrandListAPIView.as_view(), name='all-b'),
  path('<str:pk>/nearme', NearMeListAPI.as_view(), name='near_me'),

  path('update', ProfileUpdateAPI.as_view(), name='profile_update'), 
  path('<str:pk>/follow', FollowUnfollowAPI.as_view(), name='follow-unfollow-profile'),
  path('<str:pk>/removefollower', remove_followerAPI.as_view(), name='remove-follower'),

  path('<str:pk>/followers', FollowerListAPI.as_view(), name='followers'),
  path('<str:pk>/following', FollowingListAPI.as_view(), name='following'),

  # Profile Posts
  # path('<str:pk>/pvc', PVCVideosAPI.as_view() ,name='pvc'),
  # path('<str:pk>/ads', SavadsListAPI.as_view() ,name='ads'),
  # path('<str:pk>/fam', FAMListAPI.as_view(), name='fam'),
  # path('<str:pk>/org', OrgVideosListAPI.as_view() ,name='org'),

  path("search", UserVuzerAPI.as_view(), name='search-user'),
]

backend/profiles/forms.py
from django import forms
from .models import Profile
from phonenumber_field.formfields import PhoneNumberField
from phonenumber_field.widgets import PhoneNumberPrefixWidget



cat = [
  ('General', '⚫ General'),
  ('Channel', '🔴 Channel'),
  ('Masjid & Madrasa', '🟢 Masjid & Madrasa'),
  ('Organization', '🔵 Organization'),
  ('Brand', '🟠 Brand'),
] 



class ProfileModelForm(forms.ModelForm):
    phone_number = PhoneNumberField(
        label="Phone Number (will not be displayed)",
        widget=PhoneNumberPrefixWidget(initial='PK'),
        required=False, 
    )
    slogan = forms.CharField(
        max_length=80,
        label='Slogan or Favorite Line',
        required=False,
        widget=forms.TextInput(attrs={
            'placeholder': 'Leave an inspiring Line for other users (max 80 characters)'
        })
    )
    profession = forms.CharField(
        max_length=60,
        label='Profession',
        required=False,
        widget=forms.TextInput(attrs={'placeholder': 'Tell us what you do and how you make a difference as a valuable Sefarz user.'}))

    cur_add = forms.CharField(
        max_length=100,
        label='Location (e.g. City, Country)',
        required=False,
        widget=forms.TextInput(attrs={
            'placeholder': 'Street/Block, Area, Karachi, Pakistan'
        })
    )
    picture = forms.ImageField(
        widget=forms.FileInput(attrs={'type': 'file', 'accept': 'image/*' , 'style': 'width: 50em; height: auto;'}),
        required=False,
        label='Profile Picture (800 x 800 pixels)',
    )
    intro = forms.CharField(
        max_length=250,
        label='About (max 250 characters)',
        required=False,
        widget=forms.Textarea(attrs={
            'placeholder': 'Tell us a little about yourself',
            'rows': 2,
            'cols': 30
        })
    )
    bank_details = forms.CharField(
        max_length=700,
        label='Bank Details (will not be displayed)',
        required=False,
        widget=forms.Textarea(attrs={
            'placeholder': 'Provide your Bank Details or Patreon Link for Support, if you are going to create PVC',
            'rows': 1,
            'cols': 30
        })
    )

    email_notif = forms.BooleanField( 
        label='Email Notification',
        required=False,
        widget=forms.CheckboxInput(attrs={
            'class': 'form-check-input',
            'type': 'checkbox',
            'id': 'flexCheckDefault',
        })
    )

    cat = forms.CharField(
        label='Profile Category', 
        required=False, 
        widget=forms.Select(choices=cat, attrs={'placeholder': 'Select Profile Category'})
        )


    class Meta:
        model = Profile
        fields = [
            'picture',
            'slogan',
            'intro',
            'profession',
            'phone_number',
            'cur_add',
            'bank_details',
            'email_notif',
            'cat',
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for i, field in enumerate(self.fields):
            self.fields[field].widget.attrs['class'] = f'field{i+1}'
            self.fields[field].widget.attrs['id'] = f'field{i+1}'

    # def clean_picture(self):
    #     ALLOWED_IMAGE_TYPES = ['picture/jpeg', 'picture/png', 'picture/jpg']
    #     image = self.cleaned_data.get('image')
    #     if image:
    #         content_type = image.content_type
    #         if content_type not in ALLOWED_IMAGE_TYPES:
    #             message = f"This file type ({content_type}) is not supported. Please upload a JPEG, PNG, or jpg file."
    #             raise ValidationError(message)
    #     return image
    # def save(self, commit=True):
    #     instance = super().save(commit=False)

    #     # Handle file upload
    #     picture = self.cleaned_data.get('picture')
    #     if picture:
    #         instance.picture = picture.name.split('/')[-1]

    #     if commit:
    #         instance.save()

    #     return instance

backend/profiles/views.py
######### Internal ######### 
from .models import Profile
from .forms import ProfileModelForm
from .forms import ProfileModelForm
from user.models import User
from django.contrib.auth import get_user_model



######### External #########
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from .forms import ProfileModelForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from user.models import User
from django.contrib.auth import get_user_model
from notifications.signals import notify
from django.contrib import messages
from django.core.mail import send_mail
import json
from django.core.serializers.json import DjangoJSONEncoder
from django.http import JsonResponse, HttpResponseRedirect
from itertools import chain
from decouple import config
from user.models import User
ABSOLUTE_PATH = config('ABSOLUTE_PATH', cast=str, default='/app')
PRODUCTION = config('PRODUCTION', cast=bool, default=False)
INFO_EMAIL = config('INFO_EMAIL', cast=str, default='famior01@gmail.com')


################################ Rest Framwork ###############################
from rest_framework import generics
from django.contrib.auth.decorators import login_required
from rest_framework.views import APIView
from .serializers import *
from rest_framework.permissions import IsAuthenticated, AllowAny, IsAuthenticatedOrReadOnly
from rest_framework import status
from django.utils.decorators import method_decorator
from rest_framework.response import Response
############################### Functions & Classes ################################

# class PVCVideosAPI(generics.ListAPIView):
#     permission_classes = [AllowAny]

#     def get_queryset(self):
#         pk = self.kwargs.get('pk')
#         profile = get_object_or_404(Profile, user__username=pk)

#         if self.request.user.is_authenticated:
#             if self.request.user.gender == 'Male' and self.request.user != profile.user:
#                 pvc_videos = pvc.objects.filter(creator=profile, gender__iexact="Male")
#             elif self.request.user.gender == "Female" and self.request.user != profile.user:
#                 pvc_videos = pvc.objects.filter(creator=profile, gender__iexact='Female')
#             else:
#                 pvc_videos = pvc.objects.filter(creator=profile)
#         else:
#             pvc_videos = pvc.objects.filter(creator=profile, gender__iexact="Male")

#         return pvc_videos

#     def list(self, request, pk):
#         queryset = self.get_queryset()
#         serializer = PVCSerializer(queryset, many=True)
#         return Response(serializer.data)

# class FAMListAPI(generics.ListAPIView):
#     permission_classes = [AllowAny]

#     def get_queryset(self):
#         pk = self.kwargs.get('pk')
#         profile = get_object_or_404(Profile, user__username=pk)
#         return FAM.objects.filter(creator=profile)

#     def list(self, request, pk):
#         queryset = self.get_queryset()
#         serializer = self.get_serializer(queryset, many=True)
#         return Response(serializer.data)

# class OrgVideosListAPI(generics.ListAPIView):
#     serializer_class = OrgSerializer
#     permission_classes = [AllowAny]

#     def get_queryset(self):
#         pk = self.kwargs.get('pk')
#         profile = get_object_or_404(Profile, user__username=pk)
#         return Org.objects.filter(org_name=profile)

#     def list(self, request, pk):
#         queryset = self.get_queryset()
#         serializer = self.get_serializer(queryset, many=True)
#         return Response(serializer.data)

# class SavadsListAPI(generics.ListAPIView):
#     serializer_class = SavadsSerializer
#     permission_classes = [AllowAny]

#     def get_queryset(self):
#         pk = self.kwargs.get('pk')
#         profile = get_object_or_404(Profile, user__username=pk)
#         return Savads.objects.filter(creator=profile, activated=True, verified=True).order_by('-created')

#     # def list(self, request, pk):
#     #     queryset = self.get_queryset()
#     #     serializer = self.get_serializer(queryset, many=True)
#     #     return Response(serializer.data)

class ProfileDetailViewAPI(APIView):
    serializer_class = ProfileSerializer
    permission_classes = [AllowAny]

    def get(self, request, *args, **kwargs):
        pk = self.kwargs.get("pk")
        profile = get_object_or_404(Profile, user__username=pk)
        serializer = ProfileSerializer(profile)
        context = {}
        
        context['profiles'] = serializer.data

        pvc_ = pvc.objects.filter(creator=profile).all()
        org = Org.objects.filter(org_name=profile).all()
        fam = FAM.objects.filter(creator=profile).all()
        ads = Savads.objects.filter(creator=profile, activated=True, verified=True).order_by('-created')

        pvc_count, fam_count, org_count, ads_count = pvc_.count(), fam.count(), org.count(), ads.count()


        if pvc_count >= org_count and pvc_count >= fam_count and pvc_count >= ads_count:
            context['pvc_videos'] = [pvc_.values()]
            context['run_pvc'] = True
        elif org_count >= pvc_count and org_count >= fam_count and org_count >= ads_count:
            context['org_videos'] = [org.values()]
            context['run_org'] = True
        elif fam_count >= pvc_count and fam_count >= org_count and fam_count >= ads_count:
            context['zp'] = [fam.values()]
            context['run_fam'] = True
        else:
            context['all_ads'] = [ads.values()]
            context['run_ads'] = True

        return Response(context, status=status.HTTP_200_OK)


        # return Response(serializer.data)

class FollowerListAPI(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request, pk):
        user = get_object_or_404(User, username=pk)

        followers_profiles = Profile.objects.filter(following=user).exclude(user=user)
        view_profile = Profile.objects.get(user=user)

        followers_serializer = ProfileSerializer(followers_profiles, many=True)
        view_profile_serializer = ProfileSerializer(view_profile)

        # data = {
        #     'followers_profiles': followers_serializer.data,
        #     'view_profile': view_profile_serializer.data,
        # }

        return Response(followers_serializer.data, status=status.HTTP_200_OK)

class FollowingListAPI(generics.ListAPIView):
    serializer_class = ProfileSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        check_p = Profile.objects.get(user=self.request.user)
        print("check Profile,", check_p)
        if check_p.user.username == self.kwargs.get('pk'):
            pk = self.kwargs.get('pk')
            user = User.objects.get(username=pk)
            profile = Profile.objects.get(user=user)
            all_users = profile.get_following()
            following_profiles = Profile.objects.filter(user__in=all_users).exclude(user=user)
            print(following_profiles)
            return following_profiles
        else:
            return Profile.objects.none()  # Return an empty queryset if conditions are not met

class ProfileListAPI(generics.ListAPIView):
    serializer_class = ProfileSerializer
    permission_classes = [IsAuthenticatedOrReadOnly]

    def get_queryset(self):
        if self.request.user.is_authenticated:
            return recommend_profiles(self.request, general=True)
        else:
            # Return a list of general profiles for unauthenticated users
            return Profile.objects.filter(user__gender__iexact='Male').exclude(user__is_superuser=True).filter(cat='General').order_by('?')[:200]

class OrgListAPIView(generics.ListAPIView):
  serializer_class = ProfileSerializer

  def get_queryset(self):
      if self.request.user.is_authenticated:
          return recommend_profiles(self.request, org=True)
      else:
          # Return a list of general profiles for unauthenticated users
          return Profile.objects.filter(cat='Organization').exclude(user__is_superuser=True).order_by('?')[:200]

class ChannelListAPIView(generics.ListAPIView):
    serializer_class = ProfileSerializer

    def get_queryset(self):
        if self.request.user.is_authenticated:
            return recommend_profiles(self.request, channel=True)
        else:
            # Return a list of general profiles for unauthenticated users
            return Profile.objects.filter(cat='Channel').exclude(user__is_superuser=True).order_by('?')[:200]

class MListAPIView(generics.ListAPIView):
  serializer_class = ProfileSerializer

  def get_queryset(self):
      if self.request.user.is_authenticated:
          return recommend_profiles(self.request, mm=True)
      else:
          # Return a list of general profiles for unauthenticated users
          return Profile.objects.filter(cat='Masjid & Madrasa').exclude(user__is_superuser=True).order_by('?')[:200]

class BrandListAPIView(generics.ListAPIView):
  serializer_class = ProfileSerializer

  def get_queryset(self):
      if self.request.user.is_authenticated:
          return recommend_profiles(self.request, brand=True)
      else:
          # Return a list of general profiles for unauthenticated users
          return Profile.objects.filter(cat='Brand').exclude(user__is_superuser=True).order_by('?')[:200]

from collections import OrderedDict
def recommend_profiles(request, channel=False, org=False, brand=False, mm=False, general=False):
  '''
  Here, if user interact with objects of any type of user, then he will be recommended that user, e.g. if user interact with the Org object, but the profile is pvc_channel of that object, then user will be recommended with that pvc_channel on channel page
  '''
  if request.user.is_authenticated:
    user = request.user
    my_profile = Profile.objects.get(user=user)

backend/profiles/templates/profiles/Masjid&Madrasa.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
🟢Masajid and Madaris
{% endblock title %}


{% block css %}
  <link rel="stylesheet" type="text/css" href={% static 'pvc/style.css' %}>
  <link rel="stylesheet" type="text/css" href={% static 'profiles/style.css' %}>
{% endblock css %}

{% block header %}
    {% include "main/navbar.html" %}     
{% endblock header %}

{% block content %}
<div class="ui container-fluid"> 
  <div class="ui grid">
    <div class="ui row">
      <div class="three wide column" >
        {% include 'profiles/sidepanel.html' %}
      </div>

      <div class="thirteen wide column">
        <div id='profile_bannar'>
          {% comment %} <center class='top_ad_container'>
            <script type="text/javascript">
              atOptions = {
              'key' : 'a7c13fc1ce7928500af33f274437ed67',
              'format' : 'iframe',
              'height' : 50,
              'width' : 320,
              'params' : {}
              };
              document.write('<scr' + 'ipt type="text/javascript" src="http' + (location.protocol === 'https:' ? 's' : '') + '://sluicebigheartedpeevish.com/a7c13fc1ce7928500af33f274437ed67/invoke.js"></scr' + 'ipt>');
          </script>
          </center> {% endcomment %}
        </div>

        <div class="ui grid">

          <div class="ui row">
            <div class="ui ten wide column centered aligned" id='search-items'> 
              <form action="{% url 'profiles:search-user' %}" method="GET"> 
                  {% csrf_token %}
                    <div id='search_bar' class="ui right action left icon input">
                        <i class="search icon"></i>
                        <input type="hidden" name='category' value="Masjid & Madrasa">
                        <input  type="text" name='query' id='search_here' value='{{ request.GET.query }}' placeholder="Search Masajid and Madaris...">
                        <a href="{% url 'profiles:all-mm' %}">
                          <i id='cross' class="fa-solid fa-xmark ui large"></i>
                        </a>
                        <button type='submit' class="ui button">Search</button>
                    </div>
                </form>
            </div>
          </div>

          <div class="ui row">
            <div style="margin-top: 1em">
              {% if search_list %}
                <center><div class="ui green message" style='width:90%; margin-bottom:1em;' id='search_message'>  
                  <b><h3>Found {{search_list|length}} Masajid or Madaris with the name "{{request.GET.query}}"</h3></b>
                </div></center>
                
                <div class="ui four cards" id='profile_list_margins' >
                  {% for obj in  search_list %}
                      
                    <a href="{% url 'profiles:profile-detail-view' obj.user.username %}">
                      <div id='card1' class="card">
                        <div class="ui small image ">
                          <img src="{{obj.picture.url}}">
                        </div>
                        <div class="content"> 
                          <span class="header">
                            {{obj.user.full_name|truncatechars:20}}
                            {% if obj.is_org_verified %}<a data-tooltip="Verified {{obj.type_of_verified_org}}" data-position="bottom center"> <i class="check circle icon" style="color: green;"></i></a>{% endif %}
                          </span>
                          
                          <div class="meta">
                            <a href="{% url 'profiles:profile-detail-view' obj.user.username %}">
                              <span data-tooltip="Masjid or Madrasa" data-position="bottom left"><i class="fa-solid fa-at" style="color: green; margin:0px;"></i><span>{{obj.user.username|truncatechars:20}}</a>
                              {% if obj.promote %}
                              <span class="ui red mini label">Promoted</span>
                              {% endif %}
                          </div>
                          <i class="user icon"></i>
                            {{obj.get_followers|length}} Followers
                        </div>

                        {% with profile=obj %}
                          {% include 'main/follow_unfollow.html' %}
                        {% endwith %}
                      </div>
                    </a>
                  {% endfor %}
                </div>
              {% endif %}
            
            {% if m_list %}
            <!-- People to show -->
            <center><h1 id='recommendation_heading'>Masajid and Madaris</h1><hr></center>
            <div class="thirteen wide column">
              <div class="ui grid">
              <div class="ui row"  id='profile_list_margins'>
                <div class="ui four cards">
                  {% for obj in  m_list %}

                    <a href="{% url 'profiles:profile-detail-view' obj.user.username %}">
                      <div id='card1'class="card">
                        <div class="ui small image ">
                          <img src="{{obj.picture.url}}">
                        </div>
                        <div class="content">
                          <span class="header">
                            {{obj.user.full_name|truncatechars:20}}
                            {% if obj.is_org_verified %}<a data-tooltip="Verified {{obj.type_of_verified_org}}" data-position="bottom center"> <i class="check circle icon" style="color: green;"></i></a>{% endif %}
                          </span>
                          <div class="meta">
                            <a href="{% url 'profiles:profile-detail-view' obj.user.username %}">
                              <span data-tooltip="Masjid or Madrasa" data-position="bottom left"><i class="fa-solid fa-at" style="color: green; margin:0px;"></i><span>{{obj.user.username|truncatechars:20}}</a>
                              {% if obj.promote %}
                              <span class="ui red mini label">Promoted</span>
                              {% endif %}
                          </div>
                          
                          <i class="user icon"></i>
                            {{obj.get_followers|length}} Followers
                        </div>

                        {% with profile=obj %}
                          {% include 'main/follow_unfollow.html' %}
                        {% endwith %} 
                      </div>
                    </a>
                  {% endfor %}
                </div>
                {% endif %}
                
              </div>
              </div>
            </div>

            {% if not m_list and not search_list%}
                <center><div class="ui green message" style='width:90%'><b>No Masjid or Madrasa was found with the name "{{ request.GET.query }}"</b></div></center>
            {% endif %}
            </div>
          </div>




        </div>
      </div>
    </div>
  </div>
</div>


{% endblock content %}


{% comment %} 

<div class='ui segment'>
      <div class="ui grid">
        <div class="row">
          <div class="three wide column">
            <img class="ui small circular image" src="{{ obj.picture.url }}">
          </div>
          <div class="thirteen wide column">
            <h3>{{ obj.user.username }}</h3>
            <p>{{ obj.bio }}</p>
            <a href=" {% url 'profiles:profile-detail-view' obj.pk %} ">
              <button class='ui primary button sizebtn mb-5'>See Profile</button>
            </a>
            <br>
          
            {% if obj.user not in rel_receiver and obj.user not in rel_sender%}
            <form action="{% url 'profiles:send-invite' %}" method='POST'>
              {% csrf_token %}
              <input type="hidden" name='profile_pk' value={{obj.pk}}>
                <button type='submit' class='ui positive basic button sizebtn mb-5'><i class='plus square icon'></i>Add to Friends</button>
            </form>
            {% endif %}
            
            {% if obj.user in rel_receiver and request.user not in obj.friends.all %}
              <button class='ui disabled button'>
                <i class='user icon sizebtn mb-5'></i>
                Pending...
              </button>
            {% endif %}

            <!--to remove from firend list-->
            {% if request.user in obj.friends.all %}
            <form action="{% url 'profiles:remove-friend' %}" method='POST'>
              {% csrf_token %}
              <input type="hidden" name='profile_pk' value={{obj.pk}}>
              
              <button class='ui negative basic button'>
                <i class='minus square icon sizebtn mb-5'></i>
                Remove from Friends
              </button>
            </form>
            {% endif %}

          </div>
        </div>
      </div>
    </div>

{% endcomment %}









backend/profiles/templates/profiles/settings.html
{% load static %}
{% url 'user:user-update' my_profile.user.username as update_user %}
{% url 'profiles:profile_update' my_profile.pk as update_profile%}
{% url 'account_change_password' as update_password %}
{% url 'org:Verify_org' my_profile.pk as verify_org%}
{% comment %} {% url 'pvc:verify_PVC' my_profile.pk as verify_PVC%} {% endcomment %}




<div class="ui segment" id='sidepanel'>

  <div class="ui secondary vertical pointing menu">
    <a href="{{update_user}}" class="{% if request.path == update_user %}active{% endif %} item">
      <i class="fa-solid fa-pen"></i>&nbsp;&nbsp; User Info
    </a>
    <a href="{{ update_profile }}" class="{% if request.path == update_profile %}active{% endif %} item">
      <i class="fa-solid fa-pen"></i>&nbsp;&nbsp; Profile Detials
    </a>
    <a href="{{ update_password}}" class="{% if request.path == update_password %}active{% endif %} item">
      Change Password
    </a>

    <a href="{{verify_org}}" class="{% if request.path == verify_org %}active{% endif %} item">
      {% comment %} <i class="fa-solid fa-circle-check" style="color: #00ff7b;"></i> {% endcomment %}
      Verification Badge 
    </a>

    {% comment %} <a href="{{verify_PVC}}" class="{% if request.path == verify_PVC %}active{% endif %} item">
      Verify PVC Profile  <i class="check circle icon" style="color: red;"></i>
    </a> {% endcomment %}

  </div> 
</div>

backend/profiles/templates/profiles/sidepanel.html
{% load static %}
{% load myfilters %}
{% url 'profiles:all-profiles' as people %}
{% url 'profiles:all-orgs' as org %}
{% url 'profiles:all-b' as brand %}
{% url 'profiles:all-cha' as channel %}
{% url 'profiles:all-mm' as mm %}
{% url 'profiles:near_me' my_profile.user.username as near_me %}
{% url 'profiles:following' my_profile.user.username as following %}
{% url 'profiles:followers' my_profile.user.username as followers %}


<div class="ui segment" id='sidepanel'>

  <div class="ui secondary vertical pointing menu">
    <a href="{{people}}" class="{% if request.path == people %}active{% endif %} item">
      <i class="fa-solid fa-users"></i>&nbsp;&nbsp;&nbsp; Users
    </a>
    <a href="{{org}}" class="{% if request.path == org %}active{% endif %} item">
      <i class="fa-solid fa-building-ngo"></i>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Organizations
    </a>
    <a href="{{mm}}" class="{% if request.path == mm %}active{% endif %} item">
      <i class="fa-solid fa-mosque"></i>&nbsp;&nbsp; Masajid & Madaris
    </a>
    <a href="{{channel}}" class="{% if request.path == channel %}active{% endif %} item">
      <i class="fa-solid fa-circle-play"></i>&nbsp;&nbsp;&nbsp; Channels
    </a>
    <a href="{{brand}}" class="{% if request.path == brand %}active{% endif %} item">
      <i class="fa-brands fa-bandcamp"></i>&nbsp;&nbsp;&nbsp; Brands
    </a>
    
    {% if request.user.is_authenticated %}
      <a href="{{near_me}}" class="{% if request.path == near_me %}active{% endif %} item">
        <i class="fa-solid fa-people-arrows"></i>&nbsp;&nbsp; Near Me
      </a>
    {% else %}
      <a href="{% url 'account_login' %}" class="item">
        <i class="fa-solid fa-people-arrows"></i>&nbsp;&nbsp; Near Me
      </a>
    {% endif %}
    
    {% if request.user.is_authenticated %}
      <a href="{{following}}" class="{% if request.path == following %}active{% endif %} item">
        <i class="fa-solid fa-user-group"></i>&nbsp;&nbsp; Following
      </a>
    {% else %}
      <a href="{% url 'account_login' %}" class="item">
        <i class="fa-solid fa-user-group"></i>&nbsp;&nbsp; Following
      </a>
    {% endif %}

    {% if request.user.is_authenticated %}
    <a href="{{followers}}" class="{% if request.path == followers %}active{% endif %} item">
      <i class="fa-solid fa-user-group"></i>&nbsp;&nbsp; Followers
    </a>
    {% else %}
    <a href="{% url 'account_login' %}" class="item">
      <i class="fa-solid fa-user-group"></i>&nbsp;&nbsp; Followers
    </a>
    {% endif %}
      

  </div>
</div>

{% comment %} 
<div class="sidebar">
  <div class="ui segment scroll" id='tab'>
    <a href="{% url 'profiles:all-profiles' %}"  class="item" >
      <button class="ui basic black fluid small button" style='margin-bottom:10px;'>
        <i class="fa-solid fa-users" style='font-size:1em; weight:bold; margin-right:1em;'></i>
          <b>Saviors</b>
      </button>
    </a> 

    {% if request.user.is_authenticated %}
      <a href="{% url 'profiles:near_me' my_profile.user.username %}"  class="item">
        <button class="ui basic black fluid small button" style='margin-bottom:10px;'>
            <i class="fa-solid fa-people-arrows" style='font-size:1em; weight:bold; margin-right:1em;'></i>
            <b>Near Me</b>
        </button>
      </a>
    {% endif %}


    {% if request.user.is_authenticated %}
      <a href="{% url 'profiles:following' my_profile.user.username %}"  class="item">
        <button class="ui basic black fluid small button" style='margin-bottom:10px;'>
            <i class="fa-solid fa-user-group" style='font-size:1em; weight:bold; margin-right:1em;'></i>
            <b>Following</b>
        </button>
      </a>
    {% endif %}

    {% if request.user.is_authenticated %}
      <a href="{% url 'profiles:followers' my_profile.user.username %}" class="{% if request.path == show_saved %}active{% endif %} item">
        <button class="ui basic black fluid small button">
          <i class="fa-solid fa-user-group"  style='font-size:1em; weight:bold; margin-right:1em;'></i>
          <b>Followers</b>
        </button>
      </a>
    {% endif %}

    </div>
  </div> {% endcomment %}